[package]
name = "rustorm_codegen"
version = "0.1.0"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
dao = {path = "../dao"}

[lib]
proc-macro = true
